<a href="https://colab.research.google.com/github/NguyenThanhDat10012004/AIO-EXERCISE/blob/module2%2Fweek1/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
arr = np.ones((3,3), dtype = bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr = np.array([4, 6, 8, 9 , 10 , 15])
arr = arr % 2 == 1
print(arr)

[False False False  True False  True]


In [14]:
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10)

print(arr2)

[1 1 1 1 1 1 1 1 1 1]


In [15]:
import numpy as np
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [17]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB



Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 59.3MB/s]


In [29]:
def Lightness(arr):
  return (np.max(arr) + np.min(arr)) / 2
def Average(arr):
  return np.mean(arr)
def Luminosity(arr):
  return 0.21 * arr[0] + 0.72 * arr[1] + 0.08 * arr[2]

In [30]:
import matplotlib . image as mpimg
import numpy as np
img = mpimg . imread ("/content/dog.jpeg")
print(img[0, 0, :])
gray_img_01 = np.apply_along_axis(Lightness, 2, img)
print(gray_img_01 [0 , 0])
gray_img_02 = np.apply_along_axis(Average, 2, img)
print(gray_img_02 [0 , 0])
gray_img_03 = np.apply_along_axis(Luminosity, 2, img)
print(gray_img_03[0, 0])

[118 134  71]


<ipython-input-29-e86313c083dc>:2: RuntimeWarning: overflow encountered in scalar add
  return (np.max(arr) + np.min(arr)) / 2


102.5
107.66666666666667
126.94


In [31]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 15.5MB/s]


In [33]:
import pandas as pd
df = pd.read_csv ("/content/advertising.csv")
data = df.to_numpy ()
data

array([[230.1,  37.8,  69.2,  22.1],
       [ 44.5,  39.3,  45.1,  10.4],
       [ 17.2,  45.9,  69.3,  12. ],
       [151.5,  41.3,  58.5,  16.5],
       [180.8,  10.8,  58.4,  17.9],
       [  8.7,  48.9,  75. ,   7.2],
       [ 57.5,  32.8,  23.5,  11.8],
       [120.2,  19.6,  11.6,  13.2],
       [  8.6,   2.1,   1. ,   4.8],
       [199.8,   2.6,  21.2,  15.6],
       [ 66.1,   5.8,  24.2,  12.6],
       [214.7,  24. ,   4. ,  17.4],
       [ 23.8,  35.1,  65.9,   9.2],
       [ 97.5,   7.6,   7.2,  13.7],
       [204.1,  32.9,  46. ,  19. ],
       [195.4,  47.7,  52.9,  22.4],
       [ 67.8,  36.6, 114. ,  12.5],
       [281.4,  39.6,  55.8,  24.4],
       [ 69.2,  20.5,  18.3,  11.3],
       [147.3,  23.9,  19.1,  14.6],
       [218.4,  27.7,  53.4,  18. ],
       [237.4,   5.1,  23.5,  17.5],
       [ 13.2,  15.9,  49.6,   5.6],
       [228.3,  16.9,  26.2,  20.5],
       [ 62.3,  12.6,  18.3,   9.7],
       [262.9,   3.5,  19.5,  17. ],
       [142.9,  29.3,  12.6,  15. ],
 

In [37]:
max = np.max(data[:, 3])
index = np.where(data[:, 3] == max)
print(index)
print(max)

(array([175]),)
27.0


In [39]:
mean = np.mean(data[:, 0])
mean

147.0425

In [48]:
index = np.where(data[:, 3] >= 20, 1, 0)
count = np.sum(index)
count

40

In [53]:
index = np.where(data[:, 3] >= 15)
arr = np.mean(data[index, 1])
print(arr)

26.22293577981651


In [55]:
sum = np.sum(data[np.where(data[:, 2] > np.mean(data[:, 2])), 3])
print(sum)

1405.1


In [68]:
B = np.mean(data)
A = np.argmin(np.abs(data - B))
arr = np.where(data > data[A], "good", np.where(data == A, "average", "bad"))
print(arr[7 : 10])


['bad' 'bad' 'good']


In [62]:
print(data)

[22.1 10.4 12.  16.5 17.9  7.2 11.8 13.2  4.8 15.6 12.6 17.4  9.2 13.7
 19.  22.4 12.5 24.4 11.3 14.6 18.  17.5  5.6 20.5  9.7 17.  15.  20.9
 18.9 10.5 21.4 11.9 13.2 17.4 11.9 17.8 25.4 14.7 10.1 21.5 16.6 17.1
 20.7 17.9  8.5 16.1 10.6 23.2 19.8  9.7 16.4 10.7 22.6 21.2 20.2 23.7
  5.5 13.2 23.8 18.4  8.1 24.2 20.7 14.  16.  11.3 11.  13.4 18.9 22.3
 18.3 12.4  8.8 11.  17.   8.7  6.9 14.2  5.3 11.  11.8 17.3 11.3 13.6
 21.7 20.2 12.  16.  12.9 16.7 14.   7.3 19.4 22.2 11.5 16.9 16.7 20.5
 25.4 17.2 16.7 23.8 19.8 19.7 20.7 15.   7.2 12.   5.3 19.8 18.4 21.8
 17.1 20.9 14.6 12.6 12.2  9.4 15.9  6.6 15.5  7.  16.6 15.2 19.7 10.6
  6.6 11.9 24.7  9.7  1.6 17.7  5.7 19.6 10.8 11.6  9.5 20.8  9.6 20.7
 10.9 19.2 20.1 10.4 12.3 10.3 18.2 25.4 10.9 10.1 16.1 11.6 16.6 16.
 20.6  3.2 15.3 10.1  7.3 12.9 16.4 13.3 19.9 18.  11.9 16.9  8.  17.2
 17.1 20.   8.4 17.5  7.6 16.7 16.5 27.  20.2 16.7 16.8 17.6 15.5 17.2
  8.7 26.2 17.6 22.6 10.3 17.3 20.9  6.7 10.8 11.9  5.9 19.6 17.3  7.6
 14.  1